# installing assets: 'bundle install'
# local serve: 'bundle exec jekyll serve -b /shot-matcher'
# If you change this file, please restart the server process.
#
# You can access these variables via {{ site.title }}, {{ site.email }}, etc.

title: Shot Matcher
email: semagnum+shotmatcher@gmail.com
description: Official documentation
github_username: semagnum

# Build settings
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme